refactor: 💡 added gtag
Exlint/docs pull request #14
Opened 2023-02-16 16:20 UTC by roy-shiloh

added gtag

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] UI changes have been reviewed
- [x] No UI review needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-02-19 20:00 UTC, tal-rofe commented on docusaurus.config.js
> +					ignorePatterns: ['/tags/**'],
change

2023-02-19 20:00 UTC, tal-rofe commented on docusaurus.config.js
> +					anonymizeIP: true,
do you need it or not

2023-02-19 20:01 UTC, tal-rofe requested changes
change

2023-02-19 21:44 UTC, roy-shiloh commented on docusaurus.config.js
> +					anonymizeIP: true,
yes

2023-03-04 18:25 UTC, tal-rofe approved these changes

2023-03-04 18:25 UTC, merged