docs: 📘 Overall writing enhancement
Exlint/docs pull request #4
Opened 2023-02-01 10:49 UTC by roy-shiloh

Overall writing enhancement

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] UI changes have been reviewed
- [x] No UI review needed

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## What is the new behavior?

Modified docs

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-02-01 12:08 UTC, roy-shiloh commented
@amir-ben-shimol Can you resolve the checks please?

2023-02-01 12:44 UTC, roy-shiloh commented
@tal-rofe Please approve

2023-02-01 12:46 UTC, amir-ben-shimol approved these changes

2023-02-01 20:31 UTC, tal-rofe requested changes

2023-02-01 20:31 UTC, tal-rofe commented on .github/workflows/integrate.yaml
> +              run: npm install
https://github.com/Exlint/node-environment

Use this action

2023-02-01 20:31 UTC, tal-rofe commented on .github/workflows/integrate.yaml
> +              run: npm run depcheck
the repository uses `pnpm`, not `npm`

2023-02-01 20:31 UTC, tal-rofe commented on package.json
> -		"preinstall": "npx only-allow pnpm",
revert it back

2023-02-04 18:41 UTC, tal-rofe requested changes

2023-02-04 18:41 UTC, tal-rofe commented on .github/workflows/integrate.yaml
> +              uses: Exlint/node-environment@v1.1.0
you need to upgrade this action version

2023-02-04 18:41 UTC, tal-rofe commented on .github/workflows/integrate.yaml
> +    call_pnpm_caching_workflow:
dont use it and delete its file "./.github/workflows/pnpm-caching.yaml"

2023-02-04 18:41 UTC, tal-rofe commented on .github/workflows/integrate.yaml
> +    test_depcheck:
no `test_` prefix (all)

2023-02-04 18:41 UTC, tal-rofe commented on .github/workflows/integrate.yaml
> +                  node-version: 18.12.1
upgrade version

2023-02-04 18:41 UTC, tal-rofe commented on .github/workflows/integrate.yaml
> +                  package-manager-version: 7.19.0
upgrade version

2023-02-05 08:02 UTC, tal-rofe approved these changes

2023-02-05 08:03 UTC, merged